name: ardcube
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=1_gnu
  - affine=2.3.0=py_0
  - amqp=5.0.6=pyhd8ed1ab_0
  - attrs=20.3.0=pyhd3deb0d_0
  - backports=1.0=py_2
  - backports.functools_lru_cache=1.6.3=pyhd8ed1ab_0
  - bcrypt=3.2.0=py37h5e8e339_1
  - billiard=3.6.4.0=py37h5e8e339_0
  - bokeh=2.3.1=py37h89c1867_0
  - boost-cpp=1.74.0=hc6e9bd1_2
  - bzip2=1.0.8=h7f98852_4
  - c-ares=1.17.1=h7f98852_1
  - ca-certificates=2020.12.5=ha878542_0
  - cachetools=4.2.1=pyhd8ed1ab_0
  - cairo=1.16.0=h6cf1ce9_1008
  - celery=5.0.5=pyhd8ed1ab_0
  - certifi=2020.12.5=py37h89c1867_1
  - cffi=1.14.5=py37hc58025e_0
  - cfitsio=3.470=hb418390_7
  - cftime=1.4.1=py37h902c9e0_0
  - click=7.1.2=pyh9f0ad1d_0
  - click-didyoumean=0.0.3=pyh8c360ce_0
  - click-plugins=1.1.1=py_0
  - click-repl=0.1.6=py_0
  - cligj=0.7.1=pyhd8ed1ab_0
  - cloudpickle=1.6.0=py_0
  - cryptography=3.4.7=py37h5d9358c_0
  - curl=7.76.0=h979ede3_0
  - cytoolz=0.11.0=py37h5e8e339_3
  - dask=2021.4.0=pyhd8ed1ab_0
  - dask-core=2021.4.0=pyhd8ed1ab_0
  - datacube=1.8.3=py_1
  - distributed=2021.4.0=py37h89c1867_0
  - expat=2.3.0=h9c3ff4c_0
  - fiona=1.8.18=py37h527b4ca_0
  - fontconfig=2.13.1=hba837de_1004
  - freetype=2.10.4=h0708190_1
  - freexl=1.0.6=h7f98852_0
  - fsspec=0.9.0=pyhd8ed1ab_0
  - gdal=3.1.4=py37h56f316d_12
  - geopandas=0.9.0=pyhd8ed1ab_0
  - geos=3.9.1=h9c3ff4c_2
  - geotiff=1.6.0=hcf90da6_5
  - gettext=0.19.8.1=h0b5b191_1005
  - giflib=5.2.1=h36c2ea0_2
  - greenlet=1.0.0=py37hcd2ae1e_0
  - hdf4=4.2.13=h10796ff_1004
  - hdf5=1.10.6=nompi_h6a2412b_1114
  - heapdict=1.0.1=py_0
  - icu=68.1=h58526e2_0
  - importlib-metadata=3.10.0=py37h89c1867_0
  - importlib_metadata=3.10.0=hd8ed1ab_0
  - jinja2=2.11.3=pyh44b312d_0
  - jpeg=9d=h36c2ea0_0
  - json-c=0.15=h98cffda_0
  - jsonschema=3.2.0=pyhd8ed1ab_3
  - kealib=1.4.14=hcc255d8_2
  - kombu=5.0.2=py37h89c1867_2
  - krb5=1.17.2=h926e7f8_0
  - lark-parser=0.11.2=pyh44b312d_0
  - lcms2=2.12=hddcbb42_0
  - ld_impl_linux-64=2.35.1=hea4e1c9_2
  - libblas=3.9.0=8_openblas
  - libcblas=3.9.0=8_openblas
  - libcurl=7.76.0=hc4aaa36_0
  - libdap4=3.20.6=hd7c4107_2
  - libedit=3.1.20191231=he28a2e2_2
  - libev=4.33=h516909a_1
  - libffi=3.3=h58526e2_2
  - libgcc-ng=9.3.0=h2828fa1_18
  - libgdal=3.1.4=h928efbf_12
  - libgfortran-ng=9.3.0=hff62375_18
  - libgfortran5=9.3.0=hff62375_18
  - libglib=2.68.0=h3e27bee_2
  - libgomp=9.3.0=h2828fa1_18
  - libiconv=1.16=h516909a_0
  - libkml=1.3.0=h238a007_1013
  - liblapack=3.9.0=8_openblas
  - libnetcdf=4.7.4=nompi_h56d31a8_107
  - libnghttp2=1.43.0=h812cca2_0
  - libopenblas=0.3.12=pthreads_h4812303_1
  - libpng=1.6.37=h21135ba_2
  - libpq=13.1=hfd2b0eb_2
  - librttopo=1.1.0=h1185371_6
  - libsodium=1.0.18=h36c2ea0_1
  - libspatialindex=1.9.3=h9c3ff4c_3
  - libspatialite=5.0.1=h20cb978_4
  - libssh2=1.9.0=ha56f1ee_6
  - libstdcxx-ng=9.3.0=h6de172a_18
  - libtiff=4.2.0=hdc55705_0
  - libuuid=2.32.1=h7f98852_1000
  - libwebp-base=1.2.0=h7f98852_2
  - libxcb=1.13=h7f98852_1003
  - libxml2=2.9.10=h72842e0_3
  - locket=0.2.0=py_2
  - lz4-c=1.9.3=h9c3ff4c_0
  - markupsafe=1.1.1=py37h5e8e339_3
  - msgpack-python=1.0.2=py37h2527ec5_1
  - munch=2.5.0=py_0
  - ncurses=6.2=h58526e2_4
  - netcdf4=1.5.6=nompi_py37hf7b6e46_101
  - numpy=1.20.2=py37h038b26d_0
  - olefile=0.46=pyh9f0ad1d_1
  - openjpeg=2.4.0=hf7af979_0
  - openssl=1.1.1k=h7f98852_0
  - packaging=20.9=pyh44b312d_0
  - pandas=1.2.3=py37hdc94413_0
  - paramiko=2.7.2=pyh9f0ad1d_0
  - partd=1.2.0=pyhd8ed1ab_0
  - pcre=8.44=he1b5a44_0
  - pillow=8.1.2=py37h4600e1f_1
  - pip=21.0.1=pyhd8ed1ab_0
  - pixman=0.40.0=h36c2ea0_0
  - poppler=21.03.0=h93df280_0
  - poppler-data=0.4.10=0
  - postgresql=13.1=h6303168_2
  - proj=8.0.0=h277dcde_0
  - prompt-toolkit=3.0.18=pyha770c72_0
  - prompt_toolkit=3.0.18=hd8ed1ab_0
  - psutil=5.8.0=py37h5e8e339_1
  - psycopg2=2.8.6=py37h5e8e339_2
  - pthread-stubs=0.4=h36c2ea0_1001
  - pycparser=2.20=pyh9f0ad1d_2
  - pynacl=1.4.0=py37h5e8e339_2
  - pyparsing=2.4.7=pyh9f0ad1d_0
  - pyproj=3.0.1=py37h2bb2a07_1
  - pyrsistent=0.17.3=py37h5e8e339_2
  - python=3.7.10=hffdb5ce_100_cpython
  - python-dateutil=2.8.1=py_0
  - python_abi=3.7=1_cp37m
  - pytz=2021.1=pyhd8ed1ab_0
  - pyyaml=5.4.1=py37h5e8e339_0
  - rasterio=1.2.1=py37ha549118_0
  - readline=8.0=he28a2e2_2
  - redis-py=3.5.3=pyh9f0ad1d_0
  - rtree=0.9.7=py37h0b55af0_1
  - setuptools=49.6.0=py37h89c1867_3
  - shapely=1.7.1=py37hf7ed6d2_4
  - six=1.15.0=pyh9f0ad1d_0
  - snuggs=1.4.7=py_0
  - sortedcontainers=2.3.0=pyhd8ed1ab_0
  - sqlalchemy==1.3.23
  - sqlite=3.35.3=h74cdb3f_0
  - sshtunnel=0.3.1=pyhd8ed1ab_0
  - tblib=1.7.0=pyhd8ed1ab_0
  - tiledb=2.2.7=h91fcb0e_0
  - tk=8.6.10=h21135ba_1
  - toolz=0.11.1=py_0
  - tornado=6.1=py37h5e8e339_1
  - typing_extensions=3.7.4.3=py_0
  - tzcode=2021a=h7f98852_1
  - tzdata=2021a=he74cb21_0
  - vine=5.0.0=pyhd8ed1ab_1
  - wcwidth=0.2.5=pyh9f0ad1d_2
  - wheel=0.36.2=pyhd3deb0d_0
  - xarray=0.17.0=pyhd8ed1ab_0
  - xerces-c=3.2.3=h9d8b166_2
  - xorg-kbproto=1.0.7=h7f98852_1002
  - xorg-libice=1.0.10=h7f98852_0
  - xorg-libsm=1.2.3=hd9c2040_1000
  - xorg-libx11=1.7.0=h7f98852_0
  - xorg-libxau=1.0.9=h7f98852_0
  - xorg-libxdmcp=1.1.3=h7f98852_0
  - xorg-libxext=1.3.4=h7f98852_1
  - xorg-libxrender=0.9.10=h7f98852_1003
  - xorg-renderproto=0.11.1=h7f98852_1002
  - xorg-xextproto=7.3.0=h7f98852_1002
  - xorg-xproto=7.0.31=h7f98852_1007
  - xz=5.2.5=h516909a_1
  - yaml=0.2.5=h516909a_0
  - zict=2.0.0=py_0
  - zipp=3.4.1=pyhd8ed1ab_0
  - zlib=1.2.11=h516909a_1010
  - zstd=1.4.9=ha95c52a_0
  - pip:
    - chardet==4.0.0
    - geojson==2.5.0
    - geomet==0.3.0
    - html2text==2020.1.16
    - idna==2.10
    - requests==2.25.1
    - semver==2.13.0
    - sentinelsat==0.14
    - spython==0.1.12
    - tqdm==4.59.0
    - urllib3==1.26.4
